### ISSUE TITLE
Speed limit issue

### ISSUE THREAD

**Issue by dd4e** [cenkalti/rain#41]
Hello. 

I found an issue with the global download speed limit working.
I have same results for tests with and without a download speed limit.

## Input data

- golang 1.17
- github.com/cenkalti/rain v1.8.1
- used the same torrent file for both tests
- ./torrent.db and data folder clean

## Test code

```
func main() {
	var limit int64

	flag.Int64Var(&limit, "limit", 0, "download limit")
	flag.Parse()

	fmt.Printf("Global speed limit is %d KBps\n", limit)

	cfg := torrent.DefaultConfig
	cfg.DataDir = "./data"
	cfg.Database = "./torrent.db"
	cfg.SpeedLimitDownload = limit

	c, _ := torrent.NewSession(cfg)
	defer c.Close()

	f, _ := os.Open("test.torrent")
	defer f.Close()

	t, _ := c.AddTorrent(f, nil)

	for {
		select {
		case <-t.NotifyComplete():
			fmt.Println("Done!")
			return
		case <-time.Tick(10 * time.Second):
			speedKbps := t.Stats().Speed.Download / 1024
			fmt.Printf("Speed is %d KBps\n", speedKbps)
		}
	}
}
```

## Test without download limit

```
# time ./test_torrent
Global speed limit is 0 KBps
2021-11-02 12:54:52 INFO     [session] session_load.go:34 loaded 0 existing torrents
2021-11-02 12:54:52 INFO     [rpc server] session_rpc_server.go:48 RPC server is listening on 127.0.0.1:7246
2021-11-02 12:54:52 INFO     [torrent 7JTQVDvCEey413Tl-RSrzA] session_add.go:284 added torrent
2021-11-02 12:54:52 INFO     [torrent 7JTQVDvCEey413Tl-RSrzA] torrent_start.go:31 starting torrent
2021-11-02 12:54:52 INFO     [torrent 7JTQVDvCEey413Tl-RSrzA] torrent_start.go:118 Listening peers on tcp://0.0.0.0:50898
Speed is 6315 KBps
Speed is 6492 KBps
Speed is 6613 KBps
Speed is 6629 KBps
Speed is 6756 KBps
Done!
2021-11-02 12:55:43 INFO     [torrent 7JTQVDvCEey413Tl-RSrzA] torrent_write.go:82 download completed
2021-11-02 12:55:43 INFO     [torrent 7JTQVDvCEey413Tl-RSrzA] torrent_stop.go:46 stopping torrent

real    0m51,059s
user    0m8,361s
sys     0m11,401s
```

## Test with download limit

```
# time ./test_torrent --limit=1024
Global speed limit is 1024 KBps
2021-11-02 12:56:24 INFO     [session] session_load.go:34 loaded 0 existing torrents
2021-11-02 12:56:24 INFO     [rpc server] session_rpc_server.go:48 RPC server is listening on 127.0.0.1:7246
2021-11-02 12:56:24 INFO     [torrent I2naazvDEeyA0nTl-RSrzA] session_add.go:284 added torrent
2021-11-02 12:56:24 INFO     [torrent I2naazvDEeyA0nTl-RSrzA] torrent_start.go:31 starting torrent
2021-11-02 12:56:24 INFO     [torrent I2naazvDEeyA0nTl-RSrzA] torrent_start.go:118 Listening peers on tcp://0.0.0.0:55204
Speed is 6883 KBps
Speed is 7022 KBps
Speed is 6936 KBps
Speed is 6922 KBps
Speed is 6930 KBps
Done!
2021-11-02 12:57:15 INFO     [torrent I2naazvDEeyA0nTl-RSrzA] torrent_write.go:82 download completed
2021-11-02 12:57:15 INFO     [torrent I2naazvDEeyA0nTl-RSrzA] torrent_stop.go:46 stopping torrent

real    0m51,494s
user    0m8,410s
sys     0m11,407s
```

**Comment by cenkalti** [comment]
@dd4e There was a bug about the calculation of the speed limit in code. Thanks for bringing this issue. It should be fixed now. Can you verify please? Please note that the the limits are specified in kilobytes in config but they are reported in bytes from `Stats()` method.

Closing this issue now but feel free to reopen and let me know if you have questions.

**Comment by dd4e** [comment]
Thanks you @cenkalti, I've updated the go.mod to the latest version, built the test, and checked again. And I still have that issue ((

go.mod
```
require github.com/cenkalti/rain v1.8.2
```

stdout
```
# ./test_torrent --limit=1024

Global speed limit is 1024 KBps
// ...
Speed is 5529 KBps
Speed is 5768 KBps
Speed is 5956 KBps
Speed is 6162 KBps
Speed is 6328 KBps
```

ps.
I setup limit in the config "as is": `cfg.SpeedLimitDownload = 1024`   
I've calculated rate into KBps: `Stats().Speed.Download / 1024`

**Comment by cenkalti** [comment]
It's strange. It seems to be working for me.
```
[air:rain]{master}% export MAGNET='magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent'
[air:rain]{master}% echo 'speedlimitdownload: 100' > config.yaml
[air:rain]{master}% rain download -c config.yaml -t $MAGNET
2021-11-09 19:30:07 INFO     [rain] main.go:649 config loaded from: config.yaml
2021-11-09 19:30:07 INFO     [torrent TKLidEG8EeyVSPbFUNbOiw] session_add.go:284 added torrent
2021-11-09 19:30:07 INFO     [session] session_load.go:34 loaded 1 existing torrents
2021-11-09 19:30:07 INFO     [rpc server] session_rpc_server.go:48 RPC server is listening on 127.0.0.1:7246
2021-11-09 19:30:08 INFO     [torrent TKLidEG8EeyVSPbFUNbOiw] torrent_start.go:31 starting torrent
2021-11-09 19:30:08 INFO     [torrent TKLidEG8EeyVSPbFUNbOiw] torrent_start.go:118 Listening peers on tcp://0.0.0.0:6109
2021-11-09 19:30:09 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 4, Speed: 0K/s, ETA: ?
2021-11-09 19:30:10 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 0K/s, ETA: ?
2021-11-09 19:30:11 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 0K/s, ETA: ?
2021-11-09 19:30:12 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 0K/s, ETA: ?
2021-11-09 19:30:13 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 102K/s, ETA: 44m0s
2021-11-09 19:30:14 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 102K/s, ETA: 44m0s
2021-11-09 19:30:15 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 102K/s, ETA: 44m0s
2021-11-09 19:30:16 INFO     [rain] main.go:763 Status: Downloading, Progress: 0%, Peers: 11, Speed: 102K/s, ETA: 44m0s
```

Can you try with the `rain download` command to see if you can reproduce it?

Also can you try with your code again but with a much lower value? Example: `time ./test_torrent --limit=1`

I am looking into your code but nothing unusual to my eyes.

**Comment by dd4e** [comment]
@cenkalti I have found the difference between your and my tests. 
Speed reduction doesn't work with web seed's torrent. I have repeated the test with tracker only torrent file and it's work.

Can you fix the speed reduction for web seed's torrent?

**Comment by cenkalti** [comment]
It should be fix with 57c5445a57caa7a232b8093c73004b9a0e8bdeca. Can you confirm?

**Comment by dd4e** [comment]
@cenkalti this is fantastic! Everything is fine. Thank you, comrade!
